NickEwer-InfoTechTest/config/routes.rb
Rails.application.routes.draw do
  resources :photos
  root to: 'photos#index'
end

NickEwer-InfoTechTest/app/models/photo.rb
class Photo < ActiveRecord::Base

  mount_uploader :avatar, AvatarUploader

	def create
    @photo = Photo.new(photo_params)
    @photo.avatar = params[:file] #file worked
    @photo.save
	end

end

NickEwer-InfoTechTest/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
	
before_action do  
  resource = controller_name.singularize.to_sym
  method = "#{resource}_params"
  params[resource] &&= send(method) if respond_to?(method, true)
end 
end

NickEwer-InfoTechTest/app/controllers/photos_controller.rb
class PhotosController < ApplicationController
  before_action :set_photo, only: [:show, :edit, :update, :destroy]

  # GET /photos
  # GET /photos.json
  def index
    @photos = Photo.all
  end

  # GET /photos/1
  # GET /photos/1.json
  def show
  end

  # GET /photos/new
  def new
    @photo = Photo.new
  end

  # GET /photos/1/edit
  def edit
  end

  # POST /photos
  # POST /photos.json
  def create

    Excon.defaults[:ssl_verify_peer] = false

    def photo_params
      params.require(:photo).permit(:img, :thumb, :caption, :desc, :alt, :avatar)
    end

    @photo = Photo.new(photo_params)

    respond_to do |format|
      if @photo.save
        format.html { redirect_to @photo, notice: 'Photo was successfully created.' }
        format.json { render :show, status: :created, location: @photo }
      else
        format.html { render :new }
        format.json { render json: @photo.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /photos/1
  # PATCH/PUT /photos/1.json
  def update
    respond_to do |format|
      if @photo.update(photo_params)
        format.html { redirect_to @photo, notice: 'Photo was successfully updated.' }
        format.json { render :show, status: :ok, location: @photo }
      else
        format.html { render :edit }
        format.json { render json: @photo.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /photos/1
  # DELETE /photos/1.json
  def destroy
    @photo.destroy
    respond_to do |format|
      format.html { redirect_to photos_url, notice: 'Photo was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_photo
      @photo = Photo.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def photo_params
		params.require(:photo).permit(:img, :thumb, :caption, :desc, :alt)

    end
end

NickEwer-InfoTechTest/app/helpers/application_helper.rb
module ApplicationHelper
end

NickEwer-InfoTechTest/app/helpers/images_helper.rb
module ImagesHelper
end

NickEwer-InfoTechTest/app/helpers/photos_helper.rb
module PhotosHelper
end

NickEwer-InfoTechTest/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <!-- Hey guys, hope you like my code! -->
  <title>Nick Ewer - Info-Tech Test</title>
  
  <!-- Stylesheets -->
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <link rel="stylesheet" type="text/css" href="../assets/stylesheets/bootstrap.css">
  <link rel="stylesheet" type="text/css" href="../assets/stylesheets/overrides.css">
  
  <!-- Scripts -->
  <script src="../assets/javascripts/bootstrap.js"></script>
  
  <%= csrf_meta_tags %>
</head>
<body>
    <!-- Semantic Header -->
    <h1 class="hidden">Destiny: Exotic Weapons</h1>

    <!-- Main Site Container -->
	<div class="container">
	
        <!-- Title -->
        <header>
            <div class="row">
                <div class="col-sm-12">
                    <h1>DESTINY</h1>
                    <h2>EXOTIC WEAPONS</h2>
                </div>
            </div>
        </header>

        <%= yield %>

	</div>
</body>
</html>

NickEwer-InfoTechTest/app/views/photos/_form.html.erb
<%= simple_form_for(@photo, html: {class: 'form-horizontal' }) do |f| %>
	<% if @photo.errors.any? %>
		<div id="error_explanation">
		<h2><%= pluralize(@photo.errors.count, "error") %> prohibited this photo from being saved:</h2>
	
		<ul>
		<% @photo.errors.full_messages.each do |message| %>
		<li><%= message %></li>
	<% end %>
	</ul>
	</div>
	<% end %>
	
	<!-- Input Form -->
	<div class="row">
		
		<div class="col-sm-3"></div>
		<div class="col-sm-6 input-form">
	
			<h3>WEAPON DETAILS</h3>
            <%= f.input :img, input_html: {class: 'hidden'}, :label => false, :placeholder => "Caption" %>
            <%= f.input :thumb, input_html: {class: 'hidden'}, :label => false, :placeholder => "Caption" %>
			<%= f.input :caption, input_html: {class: 'form-control'}, :label => false, :placeholder => "Caption" %>
			<%= f.input :desc, input_html: {class: 'form-control'}, :label => false, :placeholder => "Description" %>
			<%= f.input :alt, input_html: {class: 'form-control'}, :label => false, :placeholder => "Alt" %>
            <%= f.input :avatar, as: :file, input_html: {class: 'form-control'}, :label => false, :placeholder => "Image" %>
			
			<div class="actions">
				<%= f.button :submit, :class => "btn btn-success btn-large float-right" %>
			</div>
		</div>
		
		<div class="col-sm-3"></div>
		
	</div>
  
<% end %>


NickEwer-InfoTechTest/app/views/photos/edit.html.erb
<nav>
    <div class="row">
      <div class="col-sm-12">
        <div class="controls">
          <%= link_to 'Back', photos_path %>
          <%= link_to 'Show', @photo %>
        </div>
      </div>
    </div>
</nav>

<%= render 'form' %>

NickEwer-InfoTechTest/app/views/photos/index.html.erb
<nav>
    <div class="row">
        <div class="col-xs-12 controls">
            <%= link_to 'New Photo', new_photo_path %>
        </div>
    </div>
</nav>

<!-- Image Thumbnails -->
<section>
    <h2 class="hidden">Image List</h2>
    <div class="image-thumbs">
            <% @count = 1 %>
            <% @photos.each do |photo| %>

                <%= if @count == 1
                    "<!-- NEW ROW --><div class='row'>".html_safe
                end %>

                <!-- OUTPUT IMAGE -->

                <div class="col-lg-3 col-md-6 col-sm-12">
                    <a href="photos/<%= photo.id %>">
                        <div class="box" style="background-image:url('<%= photo.avatar %>')">
                            <!--<img src=" <%= photo.avatar %>" alt="<%= photo.alt %>"/>-->
                        </div>
                    </a>
                </div>

                <%=  if @count == 4
                  "</div><!-- END ROW -->".html_safe
                     end %>

                <% @count+=1; %>

                <% if @count == 5
                  @count = 1
                end %>

            <% end %>

         <!-- CLOSE ROWS? -->
             <%= if @count == 2
                "<div class='col-lg-9 col-md-6 col-sm-12'></div></div><!-- END ROW -->".html_safe
             end %>
             <%= if @count == 3
                "<div class='col-lg-6 col-md-6 col-sm-12'></div></div><!-- END ROW -->".html_safe
             end %>
             <%= if @count == 4
                "<div class='col-lg-3 col-md-6 col-sm-12'></div></div><!-- END ROW -->".html_safe
             end %>

</div>
</section>

NickEwer-InfoTechTest/app/views/photos/new.html.erb
<div class="row">
  <div class="col-sm-12">
    <div class="controls">
      <%= link_to 'Back', photos_path %>
    </div>
  </div>
</div>

<%= render 'form' %>

NickEwer-InfoTechTest/app/views/photos/show.html.erb
<nav>
    <div class="controls">
        <%= link_to 'Back', photos_path %>
        <%= link_to 'Edit', edit_photo_path(@photo) %>
        <!--<a href="/photo/<%= @photo.id %>/destroy">Delete</a>-->
    </div>
</nav>

<p id="notice"><%= notice %></p>

<section>
    <h2 class="hidden">Selected Image</h2>
    <div class="row">
        <div class="col-xs-12">
            <div class="item">
                <h2><%= @photo.caption %></h2>

                <p><%= @photo.desc %></p>
                <img src="<%= @photo.avatar %>" alt="<%= @photo.alt %>"/><br>

            </div>
        </div>
    </div>
</section>